Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using olashop.Data;
using olashop.Helpers;
using olashop.Models;
using olashop.Viewmodels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace olashop.Controllers
{
    
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public CartController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        
        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");
            if (cart != null)
            {
                ViewBag.cart = cart;
                ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
                int final = 0;
                foreach (var item in cart)
                {
                    final = final + item.Quantity;
                };
                ViewBag.count = final;
            }
    
            return View();
        }

        
        public IActionResult Buy(int id)
        {
            
            if (SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart") == null)
            {
                List<RealCart> cart = new List<RealCart>();
                cart.Add(new RealCart { Product = _dbContext.Products.Find(id), Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<RealCart> cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");
                
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new RealCart { Product = _dbContext.Products.Find(id), Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");
        }

        
        public IActionResult Remove(int id)
        {
            List<RealCart> cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");
            
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<RealCart> cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");
            
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }

        private IActionResult cartcount()
        {
            List<RealCart> cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");

            return RedirectToAction("Home", "Index");
        }


        public IActionResult AddToMyCart(int id)
        {
            if (SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart") == null)
            {
                List<RealCart> cart = new List<RealCart>();
                cart.Add(new RealCart { Product = _dbContext.Products.Find(id), Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<RealCart> cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");

                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new RealCart { Product = _dbContext.Products.Find(id), Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }

            return RedirectToAction("Index","Home");
        }


    }
}

Controllers/FirstHomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace olashop.Controllers
{
    public class FirstHomeController : Controller
    {
        public IActionResult FirstIndex()
        {
            return View();
        }
    }
}

Views/Shared/Search.cshtml
@model IEnumerable<olashop.Models.Product>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<style>
    #mycart {
        height: 350px;
        border-style: solid;
        border-color: #efecec;
    }

    #mycartimg {
        height: 210px;
        z-index: 1;
    }

    #viewpro {
        visibility: visible;
        position: absolute;
        padding-top: 40%;
        text-align: center;
        opacity: 0;
    }

    #mycart:hover #viewpro {
        visibility: visible;
        position: absolute;
        padding-top: 40%;
        text-align: center;
        opacity: 1;
        z-index: 1;
    }

    #mycart:hover #mycartimg {
        opacity: .5;
        /* transform:scale(1.2);*/
    }

    .myproname {
        overflow-x: scroll;
        max-height: 24px;
    }

        .myproname::-webkit-scrollbar {
            display: none;
        }

    @@media all and (max-width: 600px;)
    {
        #smhide{
            display: none;
        }
    }
</style>

<div class="row">

    <div class="col-md-3" id="smhide">
        @await Component.InvokeAsync("Right")
    </div>

    <div class="col-md-6">
        <div class="row">
            @foreach (var item in Model)
            {


                <div class="col-md-3 m-2 p-1" id="mycart">
                    <div class="row">
                        <img src="~/uploads/@item.ImgUrl" class="col-12 m-1" id="mycartimg" />
                        <div class="col-12">
                            <p class="myproname">
                                @item.Name
                            </p>

                        </div>
                        <p class="col-12">@item.Price EGP</p>
                        @{ if (item.Quantity <= 0)
                            {
                                <p class="col-8 btn btn-secondary m-2 p-1">Not Available</p>
                            }

                            else
                            {
                                <a class="col-8 btn btn-success m-2 p-1" asp-controller="Cart" asp-action="AddToMyCart" asp-route-id="@item.Id">ADD To CART</a>
                            }
                        }


                        <div class="col-12" id="viewpro">
                            <a class=" m-2 p-1">

                                @*@(Html.Awe().InitPopup()
                              .Name("QuickProductView")
                              .Url(Url.Action("QuickProductView","Home"))
                              .Mod(o => o.OutClickClose())
                              .Draggable(false)
                              .Title("Quick View")
                              .MaxWidth(1000)
                              .Height(600)
                              )

                                @Html.Awe().Button().Text("QuickView").OnClick(Html.Awe().OpenPopup("QuickProductView").Params(new { id = item.Id }))*@
                            </a>
                        </div>

                    </div>

                </div>
            }
        </div>
    </div>

    <div class="col-md-3">

    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - olashop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/Swiper/swiper-bundle.min.css" rel="stylesheet" />
    <link href="~/Swiper/swiper-bundle.css" rel="stylesheet" />
    <link href="~/css/toastr.min.css" rel="stylesheet" />

    <link href="~/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/css/all.min.css" rel="stylesheet" />
    <link href="~/css/themes/black-cab/AwesomeMvc.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <link href="~/fontawesome-iconpicker/css/fontawesome-iconpicker.min.css" rel="stylesheet" />
</head>
<style>
    .mt
    {
        margin-top: 130px;
    }
    #carticon {
        color: #5dd0d0;
    }
    .dropdown {
        position: relative;
        display: inline-block;
        color: #82c3c3;
    }
    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 200px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }
        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }
    .dropdown:hover .dropdown-content {
        display: block;
    }

    #navbarNav{
        font-size:12px;
    }

    #searchinputlarg {
        margin: auto;
        width: 80%;
        background-color: #fbfbfb;
        border-color: white;
    }
    #lisealarg {
        width: 600px;
        margin: auto;
    }


        @@media only screen and (max-width: 768px) {
          /* For mobile phones: */
                #lisealarg
                {
                    display:none;
                }
        }

    #searchmobile
    {
        display:none;
    }
    @@media only screen and (max-width: 768px) {
        /* For mobile phones: */
        #searchmobile {
            display: inline;
        }
    }
    #searchbutt {
        color: white;
        background-color: #557ee8;
    }
</style>
<body>
    <div class="fixed-top">


        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow  mb-0">
                <div class="container mt-0">
                    <a id="carticon" asp-controller="Cart" asp-action="Index">
                        @await Component.InvokeAsync("Cart")|

                        <div class="dropdown">
                            <a class="dropbtn">

                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart-dash" viewBox="0 0 16 16">
                                    <path d="M6.5 7a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4z" />
                                    <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                                </svg>
                            </a>
                            <div class="dropdown-content">
                                @await Component.InvokeAsync("NavCart")

                            </div>
                        </div>

                    </a>








                    <div class="dropdown" id="searchmobile">
                        <a class="dropbtn">

                            <i class="fas fa-search fa-2x"></i>
                        </a>
                        <div class="dropdown-content ">
                            <form class=" form-row" asp-controller="Home" asp-action="SearchNav">
                                <input type="text" class="form-group col-8 m-auto" name="word" id="searchinputlarg" />
                                <input type="submit" class="form-group col-3 m-auto" value="Search" />
                            </form>

                        </div>
                    </div>





                    <a class="navbar-brand" asp-area="" asp-controller="FirstHome" asp-action="FirstIndex">olashop</a>



                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Dashboard">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li id="lisealarg">
                                <form class=" form-inline" asp-controller="Home" asp-action="SearchNav" method="post">
                                    <input type="text" class="form-group" name="word" id="searchinputlarg" />
                                    <button type="submit" class="btn" id="searchbutt"><i class="fas fa-search fa-2x"></i></button>
                                </form>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </header>


        @await Component.InvokeAsync("CategoryNav")

    </div>
    <div class="container-fluid">
        <main role="main" class="mt">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - olashop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/fontawesome-iconpicker/js/fontawesome-iconpicker.min.js"></script>
    <script src="~/Swiper/swiper-bundle.min.js"></script>
    <script src="~/Swiper/swiper-bundle.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script src="~/js/AwesomeMvc.js"></script>
    <script src="~/js/awem.js"></script>

    <script src="~/js/utils.js"></script>
    @*used in utils.init and sent on all post requests made by awe*@
    @Html.AntiForgeryToken()

    @*call init after utils.js and validate.js*@
    @*@Html.Awe().Init()*@

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_dashboard.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <partial name="_dashboardpartial" />
    <div>
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Views/Shared/_dashboardpartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" asp-controller="Home" asp-action="Index">Ola Shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Category
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" asp-controller="Admin" asp-action="CategoryIndex">CategoryIndex</a>
                    <a class="dropdown-item" asp-controller="Admin" asp-action="CategoryCreate">CategoryCreate</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Product
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" asp-controller="Admin" asp-action="ProductIndex">ProductIndex</a>
                    <a class="dropdown-item" asp-controller="Admin" asp-action="ProductCreate">ProductCreate</a>


                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Brand
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" asp-controller="Admin" asp-action="BrandIndex">BrandIndex</a>
                    <a class="dropdown-item" asp-controller="Admin" asp-action="BrandCreate">BrandCreate</a>


                </div>
            </li>
        </ul>
    </div>
</nav>