Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using olashop.Data;
using olashop.Helpers;
using olashop.Models;
using olashop.Viewmodels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace olashop.Controllers
{
    
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public CartController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        
        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");
            if (cart != null)
            {
                ViewBag.cart = cart;
                ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
                int final = 0;
                foreach (var item in cart)
                {
                    final = final + item.Quantity;
                };
                ViewBag.count = final;
            }
    
            return View();
        }

        
        public IActionResult Buy(int id)
        {
            
            if (SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart") == null)
            {
                List<RealCart> cart = new List<RealCart>();
                cart.Add(new RealCart { Product = _dbContext.Products.Find(id), Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<RealCart> cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");
                
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new RealCart { Product = _dbContext.Products.Find(id), Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");
        }

        
        public IActionResult Remove(int id)
        {
            List<RealCart> cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");
            
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<RealCart> cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");
            
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }

        private IActionResult cartcount()
        {
            List<RealCart> cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");

            return RedirectToAction("Home", "Index");
        }


        public IActionResult AddToMyCart(int id)
        {
            if (SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart") == null)
            {
                List<RealCart> cart = new List<RealCart>();
                cart.Add(new RealCart { Product = _dbContext.Products.Find(id), Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<RealCart> cart = SessionHelper.GetObjectFromJson<List<RealCart>>(HttpContext.Session, "cart");

                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new RealCart { Product = _dbContext.Products.Find(id), Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }

            return RedirectToAction("Index","Home");
        }


    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using olashop.Data;
using olashop.Models;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace olashop.Controllers
{
    
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _dbContext;
        public HomeController(ILogger<HomeController> logger,ApplicationDbContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var res = _dbContext.Products.ToList();
           
            return View(res);
        }

     

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        public IActionResult SearchWithCat(int id)
        {
            var res = _dbContext.Products.Where(r => r.CategoryId==id).ToList();
            return View("Search", res);

        }

        public IActionResult SearchWithPrice(int price)
        {
            var res = _dbContext.Products.Where(r => r.Price <= price).ToList();
            return View("Search", res);
        }

        public IActionResult QuickProductView(int id)
        {
            var pro = _dbContext.Products.FirstOrDefault(r => r.Id == id);

            ViewBag.pro = pro;
            return PartialView();
        }


        public IActionResult SearchNav(string word)
        {

           
            

         
             var res = _dbContext.Products.Where(r => r.Name.Contains(word) || r.Category.Name.Contains(word)).ToList();

         


            return View("Search", res);
        }
        //public IActionResult pop1()
        //{
        //    var p = _dbContext.Categories.Select(o => new KeyContent(o.Id, o.Name));

        //    return Json(p);
        //}

        //public IActionResult GetMealsSetValue(int[] categories)
        //{
        //    categories = categories ?? new int[] { };

        //    var items = _dbContext.Products.Where(o => categories.Contains(o.CategoryId)).ToList();

        //    object value = null;
        //    if (items.Any())
        //    {
        //        value = new[] { items.Skip(1).First().Id };
        //    }

        //    return Json(new AweItems
        //    {
        //        Items = items.Select(o => new KeyContent(o.Id, o.Name)),
        //        Value = value
        //    });
        //}
    }
}

ViewComponents/LeftViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using olashop.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace olashop.ViewComponents
{
    public class LeftViewComponent:ViewComponent
    {
        private readonly ApplicationDbContext _dbContext;
        public LeftViewComponent(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IViewComponentResult Invoke()
        {
            var res = _dbContext.Products.ToList();
            return View(res);
        }

    }
}

ViewComponents/RightViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using olashop.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace olashop.ViewComponents
{
    public class RightViewComponent:ViewComponent
    {
        private readonly ApplicationDbContext _dbContext;
        public RightViewComponent(ApplicationDbContext dbContext )
        {
            _dbContext = dbContext;
        }

        public IViewComponentResult Invoke()
        {
            return View(_dbContext.Categories.ToList());
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
    #main {
        overflow: scroll;
        max-height: 100vh;
    }

        #main::-webkit-scrollbar {
            display: none;
        }

    @@media all and (max-width: 768px) {
        #smhide {
            display: none;
        }
        #main{
            margin-left: 25%;
        }
    }
  
    
</style>
<script>

</script>

<div class="row">
    <div class="col-3 " id="smhide">
        @await Component.InvokeAsync("Right")
    </div>
    <div class="col-6" id="main">
        <partial name="_productlist" />

    </div>

    <div class="col-md-3 " id="smhide">
        @await Component.InvokeAsync("Left")
       
    </div>

    @*@Html.Awe().AjaxDropdown("hh").Url(Url.Action("pop1"))
  
    @Html.Awe().AjaxDropdown("add2").Url(Url.Action("pop1"))
    @Html.Awe().AjaxDropdown("add3").Url(Url.Action("pop1"))*@


</div>

Views/Home/QuickProductView.cshtml
@{
    if (ViewBag.pro != null)
    {
        <div class="row">
            <h3 class="col-12">
                @ViewBag.pro.Name
                <a>Exit</a>
            </h3>
            <hr />
            <img class="col-md-3" src="~/uploads/@ViewBag.pro.ImgUrl" />
            <div class="col-12 col-md-6">
                <div class="row">
                    <h4 class="col-12">@ViewBag.pro.Price EGP</h4>
                    <hr />
                    <p class="col-12">
                        @ViewBag.pro.Description
                    </p>
                </div>
            </div>
            <div class="col-12 col-md-3">
                <a class="btn btn-success" asp-controller="Cart" asp-action="AddToMyCart" asp-route-id="@ViewBag.pro.Id">Add to Cart</a>
            </div>

        </div>
    }
    else
    {
        <div class="row">
            <h3 class="col-12">
                please select
            </h3>



        </div>
    }
}

Views/Home/_productlist.cshtml
@model IEnumerable<olashop.Models.Product>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<style>




    @*ldmfflmg;dmf*@

    #mycart {
        height: 350px;
        border-style: solid;
        border-color: #efecec;
    }
    #mycartimg
    {
        height:210px;
        z-index:1;
    }
    #viewpro {
        visibility: visible;
        position: absolute;
        padding-top: 40%;
        text-align: center;
        opacity:0;

    }
        #mycart:hover #viewpro{
            visibility: visible;
            position: absolute;
            padding-top: 40%;
            text-align: center;
            opacity:1;
            z-index:1;
        }
    #mycart:hover #mycartimg {

        opacity: .5;

       /* transform:scale(1.2);*/


    }

    .myproname
    {
        overflow-x:scroll;
        max-height:24px;

    }
    .myproname::-webkit-scrollbar
    {
        display:none;
    }

    #qkview {
        visibility: visible;
        position: absolute;
        padding-top: 40%;
        text-align: center;
        opacity: 0;
    }
        #qkview:target {
            visibility: visible;
            position: absolute;
            padding-top: 40%;
            text-align: center;
            opacity: 1;
            z-index: 1;
        }

    #qqq {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 2; /* Sit on top */
        padding-top: 100px; /* Location of the box */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

</style>

<div class="row">

    @foreach (var item in Model)
    {




        <div class="col-md-3 m-2 p-1" id="mycart">
            <div class="row">
                <img src="~/uploads/@item.ImgUrl" class="col-12 m-1" id="mycartimg" />
                <div class="col-12">
                    <p class="myproname">
                        @item.Name
                    </p>

                </div>
                <p class="col-12">@item.Price EGP</p>
                @{ if (item.Quantity <= 0)
                    {
                        <p class="col-8 btn btn-secondary m-2 p-1">Not Available</p>
                    }

                    else
                    {
                        <a class="col-8 btn btn-success m-2 p-1" asp-controller="Cart" asp-action="AddToMyCart" asp-route-id="@item.Id">ADD To CART</a>
                    }
                }


                <div class="col-12" id="viewpro">
                    <div class="  m-2 p-1" id="vquick">


                        @*@(Html.Awe().InitPopup()
                              .Name("QuickProductView")
                              .Url(Url.Action("QuickProductView","Home"))
                              .Mod(o => o.OutClickClose())
                              .Draggable(false)
                              .Title("Quick View")
                              .MaxWidth(1000)
                              .Height(600)
                              )

                        @Html.Awe().Button().Text("QuickView").OnClick(Html.Awe().OpenPopup("QuickProductView").Params(new { id = item.Id }))*@
                    </div>
                </div>

            </div>

        </div>



    }

    <div class="col-8 m-auto" id="qqq">

       
       
        
      
    </div>



</div>

@section Scripts{

    <script type="text/javascript">
     

    </script>
}